name: Docker Build and Publish

on:
  push:
    branches:
      - main
      - web-panel-dev
    # paths:
    #   - 'Dockerfile'
    #   - 'backup.sh'

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/vaultwarden-backup

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
  
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            # 为 main 分支打上 latest 标签
            type=raw,value=latest,enable={{is_default_branch}}
            # 为所有分支打上日期版本标签，格式如: 20240520
            type=raw,value={{date 'YYYYMMDD'}}
            # 为 web-panel-dev 分支打上开发版本标签
            type=raw,value=dev,enable={{contains(github.ref, 'web-panel-dev')}}
            # 使用 git commit sha 作为 tag
            type=sha,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max